apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opensearch-metrics.fullname" . }}
  labels:
    {{- include "opensearch-metrics.labels" . | nindent 4 }}
data:
{{- with .Values.opensearch }}
  OPENSEARCH_HOST: {{ .host | quote }}
  {{- if .indexPatternRegex }}
  INDEX_PATTERN_REGEX: {{ .indexPatternRegex | quote }}
  {{- end }}
  {{- if .metricsUpdateInterval }}
  METRICS_UPDATE_INTERVAL: {{ .metricsUpdateInterval | quote }}
  {{- end }}
{{- end }}
