apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opensearch-metrics.fullname" . }}
  labels:
    {{- include "opensearch-metrics.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "opensearch-metrics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # This is for setting the Prometheus scrape annotation
        prometheus.io/scrape: "true"
        # This is for setting the Prometheus scrape port annotation
        prometheus.io/port: {{ .Values.service.port | quote }}
        # This is for setting the Prometheus scrape path annotation
        prometheus.io/path: "/metrics"
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "opensearch-metrics.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "opensearch-metrics.fullname" . }}
            - secretRef:
                name: {{ include "opensearch-metrics.fullname" . }}
          env:
            - name: PORT
              value: "{{ .Values.service.port }}"
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
